beelbe/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

urlpatterns = i18n_patterns(
        url(r'^', include('experiments.urls'))
)

urlpatterns += [
    url(r'^admin/', admin.site.urls),
]

experiments/urls.py
# coding=utf-8
# ==============================================================================
# beelbe
# Copyright © 2016 Elias F. Domingos. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from experiments.forms import ExperimentsAuthenticationForm
from . import (
    views, views_admin,
)

app_name = 'experiments'
urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='experiments:login', permanent=False)),
    url(r'^login/$', views.ExperimentsLogin.as_view(authentication_form=ExperimentsAuthenticationForm), name='login'),
    url(r'^instructions/$', views.InstructionsView.as_view(), name='instructions'),
    url(r'^(?P<session_id>[0-9]+)/test/$', views.TestView.as_view(), name='test'),
    url(r'^(?P<session_id>[0-9]+)/game/$', views.game_view, name='game'),
    url(r'^(?P<session_id>[0-9]+)/results/round/$', views.finish_round_view, name='game_round'),
    url(r'^(?P<session_id>[0-9]+)/results/$', views.results_view, name='results'),
    url(r'^(?P<session_id>[0-9]+)/game/round/$', views.finish_results_view, name='results_round'),
    url(r'^(?P<session_id>[0-9]+)/results/risk_check/wait$', views.transition_risk, name='results_risk_wait'),
    url(r'^(?P<session_id>[0-9]+)/results/risk_check/$', views.check_threshold_view, name='results_risk'),
    url(r'^(?P<session_id>[0-9]+)/userinfo/$', views.UserInfoView.as_view(), name='userinfo'),
    url(r'^(?P<session_id>[0-9]+)/thanks/$', views.ThanksView.as_view(), name='thanks'),
    url(r'^(?P<session_id>[0-9]+)/wait-sync/$', views.sync_view, name='sync'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='experiments:login'), name='logout'),
    url(r'^i18n/', include('django.conf.urls.i18n'), name='set_language'),
    # admin part
    url(r'^monitor/login$', auth_views.LoginView.as_view(), name='login_admin'),
    url(r'^monitor/$', views_admin.ExperimentsAdminView.as_view(), name='admin'),
    url(r'^monitor/(?P<session_id>[0-9]+)/$', views_admin.SessionGameView.as_view(), name='monitor'),
    url(r'^monitor/(?P<session_id>[0-9]+)/graph/$', views_admin.GraphView.as_view(), name='monitor_graph'),
    url(r'^monitor/ajax/$', views_admin.fetch_session_data, name='fetch_data'),
]

experiments/views.py
# coding=utf-8
# ==============================================================================
# beelbe
# Copyright © 2016 Elias F. Domingos. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
import json
# import the logging library
import logging

from django.contrib.auth import (login as auth_login, )
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import (LoginView, )
# from django.template import Context, Template
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import (transaction, DatabaseError, )
from django.db.models import (Sum, IntegerField, Count, F, )
from django.http import (HttpResponse, HttpResponseRedirect, )
from django.shortcuts import (get_object_or_404, render, )
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.http import is_safe_url
from django.utils.translation import get_language
from django.views import generic
from numpy import random, floor

from .constants import Constants
from .decorators import (check_game_finished, check_experiment_state)
from .forms import UserInfoForm
import comp.comprehension as comp
from .models import (
    CollectiveRiskGame, Profile, Survey, Player, GameData, RequestMonitor, Instruction, Group,
)
from .utils import calculate_final_round

# Get an instance of a logger
logger = logging.getLogger(__name__)


class ExperimentsLogin(LoginView):
    """
        Display the login form and handle the login action.
    """
    user = None

    def get_redirect_url(self):
        """Return the user-originating redirect URL if it's safe."""
        redirect_to = None

        if self.user is not None:
            redirect_to = check_user_state(self.user)

        if redirect_to is None:
            redirect_to = self.request.POST.get(
                self.redirect_field_name,
                self.request.GET.get(self.redirect_field_name, '')
            )
        url_is_safe = is_safe_url(
            url=redirect_to,
            allowed_hosts=self.get_success_url_allowed_hosts(),
            require_https=self.request.is_secure(),
        )
        return redirect_to if url_is_safe else ''

    def form_valid(self, form):
        """Security check complete. Log the user in."""
        auth_login(self.request, form.get_user())
        self.user = form.get_user()
        return HttpResponseRedirect(self.get_success_url())


def check_user_state(user):
    """
    Checks if the user's state and returns a redirect url
    :param user: user object
    :return: redirect_to_state url
    """
    redirect_to = None
    # If player was already doing the experiment, redirect to previous state
    if user.player.profile.participated:
        # Check if player in a transition:
        if user.player.profile.transition_state == Constants.STATE_TRANSITION_S2:
            # transition to state S2 is finish_results_view
            redirect_to = reverse_lazy('experiments:results_round', kwargs={'session_id': user.player.session.id})
        elif user.player.profile.transition_state == Constants.STATE_TRANSITION_S3:
            # transition to state S3 is finish_round_view
            redirect_to = reverse_lazy('experiments:game_round', kwargs={'session_id': user.player.session.id})
        elif user.player.profile.transition_state == Constants.STATE_TRANSITION_S4:
            # transition to state S4 is transition_risk
            redirect_to = reverse_lazy('experiments:results_risk_wait', kwargs={'session_id': user.player.session.id})

        if user.player.profile.experiment_state == Constants.STATE_TEST:
            redirect_to = reverse_lazy('experiments:test', kwargs={'session_id': user.player.session.id})
        elif user.player.profile.experiment_state == Constants.STATE_GAME_S2:
            redirect_to = reverse_lazy('experiments:game', kwargs={'session_id': user.player.session.id})
        elif user.player.profile.experiment_state == Constants.STATE_GAME_S3:
            redirect_to = reverse_lazy('experiments:results', kwargs={'session_id': user.player.session.id})
        elif user.player.profile.experiment_state == Constants.STATE_GAME_S4:
            redirect_to = reverse_lazy('experiments:results_risk', kwargs={'session_id': user.player.session.id})
        elif user.player.profile.experiment_state == Constants.STATE_QUIZ:
            redirect_to = reverse_lazy('experiments:userinfo', kwargs={'session_id': user.player.session.id})
        elif user.player.profile.experiment_state == Constants.STATE_FINISH:
            redirect_to = reverse_lazy('experiments:logout')

    return redirect_to


class InstructionsView(LoginRequiredMixin, generic.ListView):
    template_name = 'experiments/instructions.html'
    context_object_name = 'player'
    login_url = reverse_lazy('experiments:login')

    def get_queryset(self):
        user = get_object_or_404(User, pk=self.request.user.id)
        if user.player.profile.experiment_state == Constants.STATE_LOGIN and not user.player.profile.participated:
            # Update personal endowment only the first time the player has played the game
            game = CollectiveRiskGame.objects.get(id=user.player.session.treatment.game.id)
            Profile.objects.filter(player=user.player).update(experiment_state=Constants.STATE_INSTRUCTIONS,
                                                              transition_state=Constants.STATE_NO_TRANSITION,
                                                              private_account=game.endowment,
                                                              participated=True,
                                                              time_start_experiment=timezone.now())
            self.request.session['experiment_state'] = Constants.STATE_INSTRUCTIONS

            # If deadline is variable, then calculate last round
            if game.is_round_variable:
                if not user.player.group.finishing_round_selected:
                    final_round, trials = calculate_final_round(p=game.termination_probability,
                                                                min_round=game.min_round,
                                                                dice_faces=game.dice_faces
                                                                )
                    Group.objects.filter(id=user.player.group.id).update(finishing_round=final_round,
                                                                         dice_results=','.join(map(str, trials)),
                                                                         finishing_round_selected=True)

        return user.player

    def get_context_data(self, **kwargs):
        # first get language
        lang = get_language()
        # Call the base implementation first to get a context
        instructions = Instruction.objects.get(treatment=self.request.user.player.session.treatment, lang=lang)
        context = super(InstructionsView, self).get_context_data(**kwargs)
        page = self.request.GET.get('page')
        instructions_pages = instructions.text.split("[PAGE]")

        paginator = Paginator(instructions_pages, 1)  # show one per page
        try:
            context['instructions'] = paginator.page(page)
            context['fraction'] = (float(page) / paginator.num_pages) * 100
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            context['instructions'] = paginator.page(1)
            context['fraction'] = (1 / paginator.num_pages) * 100
        except EmptyPage:
            # If page is put of range(e.e. 9999), deliver last page of results.
            context['instructions'] = paginator.page(paginator.num_pages)
            context['fraction'] = 100.0

        return context


class TestView(LoginRequiredMixin, generic.FormView):
    template_name = 'experiments/test.html'
    form_class = comp.TestForm
    login_url = reverse_lazy('experiments:login')

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        return HttpResponseRedirect(
            reverse_lazy('experiments:results_round', kwargs={'session_id': self.request.user.player.session_id}))

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        participant = get_object_or_404(Player, pk=self.request.user.id)
        context = super(TestView, self).get_context_data(**kwargs)
        Profile.objects.filter(player=participant).update(experiment_state=Constants.STATE_TEST,
                                                          transition_state=Constants.STATE_NO_TRANSITION)
        self.request.session['experiment_state'] = Constants.STATE_TEST
        self.request.session.save()

        return context


def get_monitor_name(monitors, g_round):
    try:
        monitors.all().get(name=Constants.MONITOR_S4)
    except RequestMonitor.DoesNotExist:
        try:
            return monitors.filter(name__iregex=r"\ymonitorS{0}r{1}\y".format('[2-3]', g_round)).order_by('-name')[
                0].name
        except IndexError:
            raise
    else:
        return Constants.MONITOR_S4

experiments/templates/experiments/admin/base.html
{% load static %}
{% load i18n %}

<title>{% block title %}{% trans "BEEL-Experiments" %}{% endblock %}</title>

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3-theme-blue-grey.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<body class="w3-theme-l4" style="font-family: 'Raleway', sans-serif; font-size: 16px">
<div style="min-width:400px">
    <div class="w3-bar w3-black w3-card-4">
        {% block menubar %}
            <span class="w3-bar-item w3-green w3-padding-16 w3-xlarge">BEEL</span>
            <span class="w3-bar-item w3-padding-16 w3-xlarge">{% block headname %}{% endblock %}</span>
            <div class="w3-bar-item w3-right">
                <img src="{% static "experiments/images/logo4_0.png" %}"
                     style="width:48px;height:48px;">
                <img src="{% static "experiments/images/ulbgiggrand.gif" %}"
                     style="width:48px;height:48px;">
                <img src="{% static "experiments/images/fwo_blokbeeld.jpeg" %}"
                     style="width:48px;height:48px;">
            </div>
        {% endblock %}
    </div>

    <div id="content" class="w3-container">
        {% block content %}
        {% endblock %}
    </div>

</div>
</body>

experiments/templates/experiments/admin/experiment_admin.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}"/>{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block content %}
    <div id="content-main">
        <div class="w3-bar w3-light-grey w3-border">
            <a href="#" class="w3-bar-item w3-button w3-green"><i class="fa fa-home"></i></a>
            <a href="#" class="w3-bar-item w3-button"><i class="fa fa-search"></i></a>
            <a href="#" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i></a>
            <a href="#" class="w3-bar-item w3-button"><i class="fa fa-globe"></i></a>
            <a href="#" class="w3-bar-item w3-button"><i class="fa fa-sign-in"></i></a>
        </div>
        <div class="w3-row w3-margin-top">
            <div class="w3-col m3 w3-white w3-card-2 w3-center">
            </div>
            <div class="w3-col m1 w3-center"><p></p></div>
            <div class="w3-col m8 w3-white w3-card-2">
            </div>
        </div>
    </div>

{% endblock %}

experiments/templates/experiments/admin/index.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}"/>{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block content %}
    <div id="content-main">
        <div class="w3-row w3-margin-top">
            <div class="w3-col m3 w3-white w3-card-2 w3-center">
                <header class="w3-container w3-green">
                    <h3>{% trans "Select experiment to run now" %}</h3>
                </header>
                <form class="w3-border-0 w3-margin-top" id="exp-update" method="post">
                    {% csrf_token %}
                    <div class="w3-reponsive">
                        {{ form.as_p }}
                    </div>
                    <button type="submit" value="run" class="btn btn-info">{% trans "Update" %}</button>
                </form>
            </div>
            <div class="w3-col m1 w3-center"><p></p></div>
            <div class="w3-col m8 w3-white w3-card-2">
                <header class="w3-container w3-blue w3-center">
                    {% blocktrans with experiment_name=session.experiment.experiment_name treatment_name=session.treatment.treatment_name session_number=session.session_number%}
                        Experiment: {{ experiment_name }} | Treatment: {{ treatment_name }} | Session: {{ session_number }}
                    {% endblocktrans %}
                    <h3>{% trans "Players" %}</h3>
                </header>
                <table class="w3-table w3-striped w3-hoverable">
                    <tr>
                        <th>User</th>
                        <th>Player</th>
                        <th>Private account</th>
                        <th>group</th>
                        <th>participated</th>
                        <th>finished</th>
                        <th>experiment state</th>
                        <th>language</th>
                        <th>time_start_experiment</th>
                    </tr>
                    {% for player in players %}
                        <tr>
                            <td>{{ player.user }}</td>
                            <td>{{ player.pk }}</td>
                            <td>{{ player.profile.private_account }}</td>
                            <td>{{ player.group.group_number }}</td>
                            <td>{{ player.profile.participated }}</td>
                            <td>{{ player.profile.finished }}</td>
                            <td>{{ player.profile.experiment_state }}</td>
                            <td>{{ player.profile.language }}</td>
                            <td>{{ player.profile.time_start_experiment }}</td>
                        </tr>
                    {% endfor %}
                </table>
                <a href="{% url 'experiments:monitor' run_now.session_id %}"
                   class="btn btn-info center-block">{% trans "Monitor Game" %}</a>
            </div>
        </div>
    </div>

{% endblock %}

experiments/templates/experiments/admin/monitor.html
{% extends "admin/base_site.html" %}
{% load static %}
{% load i18n %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a> &rsaquo;
        <a href="{% url 'experiments:admin' %}">{% trans 'Experiments admin' %}</a>
        {% block crumbs %}
            {% if title %} &rsaquo; {{ title }}{% endif %}
        {% endblock %}
    </div>
{% endblock %}

{% block content %}

    <h1>Monitor Session {{ session.id }}</h1>
    <div class="w3-row w3-margin-top w3-margin-bottom">
        {% for group in groups %}
            <div class="w3-col m3 w3-white w3-card-2 w3-center">
                <header class="w3-container w3-green">
                    <h3>{% blocktrans with group.group_number as group_number %}Group
                        {{ group_number }} {% endblocktrans %}</h3>
                    {% if deadline_variable %}
                        {% blocktrans with group.finishing_round as finishing_round and group.dice_results as dice_results %}
                            final round: {{ finishing_round }} dice_results: {{ dice_results }}
                        {% endblocktrans %}
                    {% endif %}
                </header>
                <table class="w3-table w3-striped w3-hoverable">
                    <tr>
                        <th>User</th>
                        <th>Player</th>
                        <th>Private account</th>
                        <th>experiment state</th>
                        <th>transition state</th>
                        <th>active</th>
                        <th>current round</th>
                        <th>threshold state</th>
                        <td>euros</td>
                    </tr>
                    {% for member in group.members.all %}
                        <tr>
                            <td>{{ member.user }}</td>
                            <td>{{ member.pk }}</td>
                            <td>{{ member.profile.private_account }}</td>
                            <td>{{ member.profile.experiment_state }}</td>
                            <td>{{ member.profile.transition_state }}</td>
                            <td>{{ member.user.is_active }}</td>
                            <td>{{ member.profile.last_round }}</td>
                            <td>{{ member.profile.get_threshold_state_display }}</td>
                            <td>{{ member.profile.get_value_in_euros }}</td>
                        </tr>
                    {% empty %}
                        {% trans "No active members in the group." %}
                    {% endfor %}
                </table>
                <div>
                    <h5>{% trans "Public account" %}</h5>
                    <div class="w3-dark-grey w3-round-large w3-margin-bottom">
                        <div class="w3-container w3-blue w3-round-large w3-center"
                             style="width:{{ group.public_account }}%">{{ group.public_account }}/{{ threshold }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="w3-col s1 w3-center"><p></p></div>
        {% endfor %}
    </div>
    <a href="{% url 'experiments:admin' %}" class="btn btn-info">{% trans "Back to admin" %}</a>

{% endblock %}

experiments/templates/experiments/admin/visualize_session.html
{% extends "admin/base_site.html" %}
{% load static %}
{% load i18n %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href={% static "experiments/css/admin_graph.css" %}>
{% endblock %}

{% block javascript %}
    <script src={% static "experiments/scripts/jquery-3.2.0.min.js" %}></script>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <script src={% static "experiments/scripts/plotresadmin.js" %}></script>

{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a> &rsaquo;
        <a href="{% url 'experiments:admin' %}">{% trans 'Experiments admin' %}</a>
        {% block crumbs %}
            {% if title %} &rsaquo; {{ title }}{% endif %}
        {% endblock %}
    </div>
{% endblock %}

{% block content %}

    <h1>Monitor Session {{ session.id }}</h1>
    <div id="id_plot_session" class="js-plot-results" data-url={% url "experiments:fetch_data" %}>
    <div id="id_sess_data_table" class="js-data-table"></div>
    </div>


    <a href="{% url 'experiments:admin' %}" class="btn btn-info">{% trans "Back to admin" %}</a>

{% endblock %}