beelbe/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

urlpatterns = i18n_patterns(
        url(r'^', include('experiments.urls'))
)

urlpatterns += [
    url(r'^admin/', admin.site.urls),
]

experiments/urls.py
# coding=utf-8
# ==============================================================================
# beelbe
# Copyright © 2016 Elias F. Domingos. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from experiments.forms import ExperimentsAuthenticationForm
from . import (
    views, views_admin,
)

app_name = 'experiments'
urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='experiments:login', permanent=False)),
    url(r'^login/$', views.ExperimentsLogin.as_view(authentication_form=ExperimentsAuthenticationForm), name='login'),
    url(r'^instructions/$', views.InstructionsView.as_view(), name='instructions'),
    url(r'^(?P<session_id>[0-9]+)/test/$', views.TestView.as_view(), name='test'),
    url(r'^(?P<session_id>[0-9]+)/game/$', views.game_view, name='game'),
    url(r'^(?P<session_id>[0-9]+)/results/round/$', views.finish_round_view, name='game_round'),
    url(r'^(?P<session_id>[0-9]+)/results/$', views.results_view, name='results'),
    url(r'^(?P<session_id>[0-9]+)/game/round/$', views.finish_results_view, name='results_round'),
    url(r'^(?P<session_id>[0-9]+)/results/risk_check/wait$', views.transition_risk, name='results_risk_wait'),
    url(r'^(?P<session_id>[0-9]+)/results/risk_check/$', views.check_threshold_view, name='results_risk'),
    url(r'^(?P<session_id>[0-9]+)/userinfo/$', views.UserInfoView.as_view(), name='userinfo'),
    url(r'^(?P<session_id>[0-9]+)/thanks/$', views.ThanksView.as_view(), name='thanks'),
    url(r'^(?P<session_id>[0-9]+)/wait-sync/$', views.sync_view, name='sync'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='experiments:login'), name='logout'),
    url(r'^i18n/', include('django.conf.urls.i18n'), name='set_language'),
    # admin part
    url(r'^monitor/login$', auth_views.LoginView.as_view(), name='login_admin'),
    url(r'^monitor/$', views_admin.ExperimentsAdminView.as_view(), name='admin'),
    url(r'^monitor/(?P<session_id>[0-9]+)/$', views_admin.SessionGameView.as_view(), name='monitor'),
    url(r'^monitor/(?P<session_id>[0-9]+)/graph/$', views_admin.GraphView.as_view(), name='monitor_graph'),
    url(r'^monitor/ajax/$', views_admin.fetch_session_data, name='fetch_data'),
]

experiments/views.py
# coding=utf-8
# ==============================================================================
# beelbe
# Copyright © 2016 Elias F. Domingos. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
import json
# import the logging library
import logging

from django.contrib.auth import (login as auth_login, )
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import (LoginView, )
# from django.template import Context, Template
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import (transaction, DatabaseError, )
from django.db.models import (Sum, IntegerField, Count, F, )
from django.http import (HttpResponse, HttpResponseRedirect, )
from django.shortcuts import (get_object_or_404, render, )
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.http import is_safe_url
from django.utils.translation import get_language
from django.views import generic
from numpy import random, floor

from .constants import Constants
from .decorators import (check_game_finished, check_experiment_state)
from .forms import UserInfoForm
import comp.comprehension as comp
from .models import (
    CollectiveRiskGame, Profile, Survey, Player, GameData, RequestMonitor, Instruction, Group,
)
from .utils import calculate_final_round

# Get an instance of a logger
logger = logging.getLogger(__name__)


class ExperimentsLogin(LoginView):
    """
        Display the login form and handle the login action.
    """
    user = None

    def get_redirect_url(self):
        """Return the user-originating redirect URL if it's safe."""
        redirect_to = None

        if self.user is not None:
            redirect_to = check_user_state(self.user)

        if redirect_to is None:
            redirect_to = self.request.POST.get(
                self.redirect_field_name,
                self.request.GET.get(self.redirect_field_name, '')
            )
        url_is_safe = is_safe_url(
            url=redirect_to,
            allowed_hosts=self.get_success_url_allowed_hosts(),
            require_https=self.request.is_secure(),
        )
        return redirect_to if url_is_safe else ''

    def form_valid(self, form):
        """Security check complete. Log the user in."""
        auth_login(self.request, form.get_user())
        self.user = form.get_user()
        return HttpResponseRedirect(self.get_success_url())


def check_user_state(user):
    """
    Checks if the user's state and returns a redirect url
    :param user: user object
    :return: redirect_to_state url
    """
    redirect_to = None
    # If player was already doing the experiment, redirect to previous state
    if user.player.profile.participated:
        # Check if player in a transition:
        if user.player.profile.transition_state == Constants.STATE_TRANSITION_S2:
            # transition to state S2 is finish_results_view
            redirect_to = reverse_lazy('experiments:results_round', kwargs={'session_id': user.player.session.id})
        elif user.player.profile.transition_state == Constants.STATE_TRANSITION_S3:
            # transition to state S3 is finish_round_view
            redirect_to = reverse_lazy('experiments:game_round', kwargs={'session_id': user.player.session.id})
        elif user.player.profile.transition_state == Constants.STATE_TRANSITION_S4:
            # transition to state S4 is transition_risk
            redirect_to = reverse_lazy('experiments:results_risk_wait', kwargs={'session_id': user.player.session.id})

        if user.player.profile.experiment_state == Constants.STATE_TEST:
            redirect_to = reverse_lazy('experiments:test', kwargs={'session_id': user.player.session.id})
        elif user.player.profile.experiment_state == Constants.STATE_GAME_S2:
            redirect_to = reverse_lazy('experiments:game', kwargs={'session_id': user.player.session.id})
        elif user.player.profile.experiment_state == Constants.STATE_GAME_S3:
            redirect_to = reverse_lazy('experiments:results', kwargs={'session_id': user.player.session.id})
        elif user.player.profile.experiment_state == Constants.STATE_GAME_S4:
            redirect_to = reverse_lazy('experiments:results_risk', kwargs={'session_id': user.player.session.id})
        elif user.player.profile.experiment_state == Constants.STATE_QUIZ:
            redirect_to = reverse_lazy('experiments:userinfo', kwargs={'session_id': user.player.session.id})
        elif user.player.profile.experiment_state == Constants.STATE_FINISH:
            redirect_to = reverse_lazy('experiments:logout')

    return redirect_to


class InstructionsView(LoginRequiredMixin, generic.ListView):
    template_name = 'experiments/instructions.html'
    context_object_name = 'player'
    login_url = reverse_lazy('experiments:login')

    def get_queryset(self):
        user = get_object_or_404(User, pk=self.request.user.id)
        if user.player.profile.experiment_state == Constants.STATE_LOGIN and not user.player.profile.participated:
            # Update personal endowment only the first time the player has played the game
            game = CollectiveRiskGame.objects.get(id=user.player.session.treatment.game.id)
            Profile.objects.filter(player=user.player).update(experiment_state=Constants.STATE_INSTRUCTIONS,
                                                              transition_state=Constants.STATE_NO_TRANSITION,
                                                              private_account=game.endowment,
                                                              participated=True,
                                                              time_start_experiment=timezone.now())
            self.request.session['experiment_state'] = Constants.STATE_INSTRUCTIONS

            # If deadline is variable, then calculate last round
            if game.is_round_variable:
                if not user.player.group.finishing_round_selected:
                    final_round, trials = calculate_final_round(p=game.termination_probability,
                                                                min_round=game.min_round,
                                                                dice_faces=game.dice_faces
                                                                )
                    Group.objects.filter(id=user.player.group.id).update(finishing_round=final_round,
                                                                         dice_results=','.join(map(str, trials)),
                                                                         finishing_round_selected=True)

        return user.player

    def get_context_data(self, **kwargs):
        # first get language
        lang = get_language()
        # Call the base implementation first to get a context
        instructions = Instruction.objects.get(treatment=self.request.user.player.session.treatment, lang=lang)
        context = super(InstructionsView, self).get_context_data(**kwargs)
        page = self.request.GET.get('page')
        instructions_pages = instructions.text.split("[PAGE]")

        paginator = Paginator(instructions_pages, 1)  # show one per page
        try:
            context['instructions'] = paginator.page(page)
            context['fraction'] = (float(page) / paginator.num_pages) * 100
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            context['instructions'] = paginator.page(1)
            context['fraction'] = (1 / paginator.num_pages) * 100
        except EmptyPage:
            # If page is put of range(e.e. 9999), deliver last page of results.
            context['instructions'] = paginator.page(paginator.num_pages)
            context['fraction'] = 100.0

        return context


class TestView(LoginRequiredMixin, generic.FormView):
    template_name = 'experiments/test.html'
    form_class = comp.TestForm
    login_url = reverse_lazy('experiments:login')

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        return HttpResponseRedirect(
            reverse_lazy('experiments:results_round', kwargs={'session_id': self.request.user.player.session_id}))

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        participant = get_object_or_404(Player, pk=self.request.user.id)
        context = super(TestView, self).get_context_data(**kwargs)
        Profile.objects.filter(player=participant).update(experiment_state=Constants.STATE_TEST,
                                                          transition_state=Constants.STATE_NO_TRANSITION)
        self.request.session['experiment_state'] = Constants.STATE_TEST
        self.request.session.save()

        return context


def get_monitor_name(monitors, g_round):
    try:
        monitors.all().get(name=Constants.MONITOR_S4)
    except RequestMonitor.DoesNotExist:
        try:
            return monitors.filter(name__iregex=r"\ymonitorS{0}r{1}\y".format('[2-3]', g_round)).order_by('-name')[
                0].name
        except IndexError:
            raise
    else:
        return Constants.MONITOR_S4

experiments/templates/experiments/base.html
{% load static %}
{% load i18n %}

<title>{% block title %}{% trans "BEEL-Experiments" %}{% endblock %}</title>

<link rel="stylesheet" type="text/css" href="{% static 'experiments/css/style.css' %}"/>
<link rel="stylesheet" href="{% static 'experiments/css/w3.css' %}">
<link rel="stylesheet" href="{% static 'experiments/css/w3-theme-blue-grey.css' %}">
<link rel="stylesheet" href="{% static 'experiments/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'experiments/bootstrap-4/css/bootstrap.min.css' %}">

<script src="{% static 'experiments/scripts/jquery-3.2.0.min.js' %}"></script>
<script src="{% static 'experiments/bootstrap-4/js/bootstrap.min.js' %}"></script>

<body class="w3-theme-l4" style="font-family: 'Raleway', sans-serif; font-size: 16px">
<div style="min-width:400px">
    <div class="w3-bar w3-black w3-card-4">
        {% block menubar %}
            <span class="w3-bar-item w3-green w3-padding-16 w3-xlarge">BEEL</span>
            <span class="w3-bar-item w3-padding-16 w3-xlarge">{% block headname %}{% endblock %}</span>
            <div class="w3-bar-item w3-right">
                <img src="{% static "experiments/images/logo4_0.png" %}"
                     style="width:48px;height:48px;">
                <img src="{% static "experiments/images/ulbgiggrand.gif" %}"
                     style="width:48px;height:48px;">
                <img src="{% static "experiments/images/fwo_blokbeeld.jpeg" %}"
                     style="width:48px;height:48px;">
            </div>
        {% endblock %}
    </div>

    <div id="content" class="w3-container w3-content w3-margin-8">
        {% block content %}
        {% endblock %}
    </div>

    <div id="footer" class="w3-container w3-black w3-bottom w3-padding-large w3-margin-top-16">
        <span class="w3-right"> Created by <a style="text-decoration: none;color:cadetblue"
                                              href="https://twitter.com/esocrats">@esocrats</a></span>
    </div>
</div>
</body>

<script>
    $(document).ready(function () {
        window.location.hash = "no-back-button";
        window.location.hash = "Again-No-back-button";//again because google chrome don't insert first hash into history
        window.onhashchange = function () {
            window.location.hash = "no-back-button";
        }
    });
</script>

experiments/templates/experiments/base_deprecated.html
{% load static %}
{% load i18n %}

<title>{% block title %}{% trans "BEEL-Experiments" %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% static 'experiments/style.css' %}"/>
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">

<div class="bkimg w3-display-container w3-animate-opacity w3-text-white">
    <div id="w3-container menubar">
        {% block menubar %}
        <div class="w3-display-topleft w3-padding-large w3-xlarge">
            Brussels Experimental Economics Laboratory
        </div>

        <div class="w3-container w3-display-topright w3-padding-large">

                <img src="{% static "experiments/images/logo4_0.png" %}" style="width:48px;height:48px;">
                <img src="{% static "experiments/images/ulbgiggrand.gif" %}" style="width:48px;height:48px;">
                <img src="{% static "experiments/images/fwo_blokbeeld.jpeg" %}" style="width:48px;height:48px;">
        </div>
        {% endblock %}
    </div>

    <div id="content" class="w3-container w3-display-middle">
        {% block content %}
        {% endblock %}
    </div>

    <div id="footer" class="w3-container w3-display-bottomleft w3-padding-large">
        Created by <a style="text-decoration: none;color:cadetblue" href="https://twitter.com/esocrats">@esocrats</a>
    </div>
</div>

experiments/templates/experiments/base_game.html
{% load static %}
{% load i18n %}

<title>{% block title %}{% trans "BEEL-Experiments" %}{% endblock %}</title>

<!-- <link rel="stylesheet" type="text/css" href="{% static 'experiments/css/style.css' %}"/> -->
<link rel="stylesheet" href="{% static 'experiments/css/w3.css' %}">
<link rel="stylesheet" href="{% static 'experiments/css/w3-theme-blue-grey.css' %}">
<link rel="stylesheet" href="{% static 'experiments/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'experiments/bootstrap-4/css/bootstrap.min.css' %}">

<script src="{% static 'experiments/scripts/jquery-3.2.0.min.js' %}"></script>
<script src="{% static 'experiments/bootstrap-4/js/bootstrap.min.js' %}"></script>
{% block optional_scripts %}
    <script src="{% static 'experiments/scripts/gameman.js' %}"></script>
{% endblock %}

<body class="w3-theme-l4" style="font-family: 'Raleway', sans-serif; font-size: 16px">
<div style="min-width:400px">

    <div id="content" class="w3-container w3-content w3-center w3-margin-8">
        {% block content %}
        {% endblock %}
    </div>

</div>
</body>

<script type="text/javascript">
    $(document).ready(function () {
        window.location.hash = "no-back-button";
        window.location.hash = "Again-No-back-button";//again because google chrome don't insert first hash into history
        window.onhashchange = function () {
            window.location.hash = "no-back-button";
        };
        $(window).on("beforeunload", function (event) {
            var confirmationMessage = "Please, don't continue! Call one of the experimenters!";
            event.returnValue = confirmationMessage;
            return confirmationMessage;
        });
        $("button").click(function (event) {
            $(window).off("beforeunload");
        });
        $("input").click(function (event) {
            $(window).off("beforeunload");
        });
        $("a").click(function (event) {
            $(window).off("beforeunload");
        });

    });
</script>

experiments/templates/experiments/base_no_footer.html
{% load static %}
{% load i18n %}

<title>{% block title %}{% trans "BEEL-Experiments" %}{% endblock %}</title>

<link rel="stylesheet" type="text/css" href="{% static 'experiments/css/style.css' %}"/>
<link rel="stylesheet" href="{% static 'experiments/css/w3.css' %}">
<link rel="stylesheet" href="{% static 'experiments/css/w3-theme-blue-grey.css' %}">
<link rel="stylesheet" href="{% static 'experiments/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'experiments/bootstrap-4/css/bootstrap.min.css' %}">

<script src="{% static 'experiments/scripts/jquery-3.2.0.min.js' %}"></script>
<script src="{% static 'experiments/bootstrap-4/js/bootstrap.min.js' %}"></script>

<body class="w3-theme-l4" style="font-family: 'Raleway', sans-serif; font-size: 16px">
<div style="min-width:400px">
    <div class="w3-bar w3-black w3-card-4">
        {% block menubar %}
            <span class="w3-bar-item w3-green w3-padding-16 w3-xlarge">BEEL</span>
            <span class="w3-bar-item w3-padding-16 w3-xlarge">{% block headname %}{% endblock %}</span>
            <div class="w3-bar-item w3-right">
                <img src="{% static "experiments/images/logo4_0.png" %}"
                     style="width:48px;height:48px;">
                <img src="{% static "experiments/images/ulbgiggrand.gif" %}"
                     style="width:48px;height:48px;">
                <img src="{% static "experiments/images/fwo_blokbeeld.jpeg" %}"
                     style="width:48px;height:48px;">
            </div>
        {% endblock %}
    </div>

    <div id="content" class="w3-container w3-content w3-margin-8">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>

<script>
    $(document).ready(function () {
        window.location.hash = "no-back-button";
        window.location.hash = "Again-No-back-button";//again because google chrome don't insert first hash into history
        window.onhashchange = function () {
            window.location.hash = "no-back-button";
        }
    });
</script>

experiments/templates/experiments/game.html
{% extends "experiments/base_game.html" %}
{% load static %}
{% load i18n %}
{% load l10n %}


{% block title %}{% trans "BEEL-Experiment" %}{% endblock %}

{% block content %}
    <div class="w3-row w3-margin-top">
        <div class="w3-light-grey w3-round-large w3-margin-bottom">
            <div class="w3-container w3-blue w3-round-large w3-center"
                 style="width:{{ round.percentage|unlocalize }}%">
                {% if is_round_variable %}
                    {% blocktrans with current_round=round.norm total_rounds=round.total_rounds %}
                        round {{ current_round }} of minimum {{ total_rounds }}
                    {% endblocktrans %}
                {% else %}
                    {% blocktrans with current_round=round.norm total_rounds=round.total_rounds %}
                        round {{ current_round }} of {{ total_rounds }}
                    {% endblocktrans %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="w3-row">

        {#    The table should be dimmed in the first round when there is no data available#}

        <div class="w3-col m9 l9 w3-padding-right">
            <div class="w3-row w3-white w3-card-2">
                <header class="w3-container bg-info text-white w3-center w3-padding-top">
                    <h3 class="w3-text-white">{% trans "Donations of the previous round" %}</h3>
                </header>
                {% if last_round_actions_others or player_last_action %}
                    <table class="w3-table w3-hoverable">
                        <tr>
                            <th class="w3-light-blue text-white w3-border-bottom w3-border-cyan text-center">{% trans "You" %}</th>
                            <th class="w3-border-bottom text-center" colspan="{{ last_round_actions_others|length }}">
                                {% trans "Other members of the group" %}
                            </th>
                        </tr>
                        <tr>
                            <td class="w3-light-blue text-white w3-border-right text-center">{{ player_last_action }}</td>
                            {% for action in last_round_actions_others %}
                                <td class="text-center">{{ action }}</td>
                            {% endfor %}
                        </tr>
                    </table>
                {% else %}
                    {% trans "No actions to show" %}
                {% endif %}
            </div>
            <div class="w3-row w3-panel w3-white w3-card-2 w3-display-container w3-padding-16">
                <div class="w3-margin-top w3-large">
                    <p class="w3-left-align w3-border-bottom">
                        {% blocktrans %}
                            How many {{ currency_name }} do you want to contribute to the public account in this
                            round?
                        {% endblocktrans %}
                    </p>
                    <p>
                        {% trans "Select one of the following options." %}
                    </p>
                    <form class="w3-center" id="rdaction"
                          action="{% url 'experiments:game_round' player.session_id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" id="roundstarts" name="time_round_start" value="0">
                        <input type="hidden" id="roundends" name="time_round_end" value="0">
                        <input type="hidden" id="timeelapsed" name="time_elapsed" value="0">
                        <input type="hidden" id="actionhid" name="action" value="0">
                        {% for action_value in valid_actions %}
                            {% if player.profile.private_account|add:"0" < action_value|add:"0" %}
                                <button type="submit" class="btn btn-info btn-lg" name="action_btn"
                                        value="{{ action_value }}" disabled>{{ action_value }}
                                </button>
                            {% else %}
                                <button type="submit" class="btn btn-info btn-lg" name="action_btn"
                                        value="{{ action_value }}">{{ action_value }}
                                </button>
                            {% endif %}
                        {% endfor %}
                    </form>
                </div>
            </div>
        </div>
        <div class="w3-col m3 l3 w3-padding-left">
            <div class="w3-row w3-white w3-card-2" id="countcontainer">
                <header class="w3-container bg-info text-white w3-center w3-padding-top">
                    <h3>{% trans "Time left" %}</h3>
                </header>
                <h3 id="countdown" class="w3-center w3-padding-top">
                    <span class="minutes">2</span>:<span class="seconds">00</span>
                </h3>

            </div>
            <div class="w3-row w3-white w3-card-2 w3-margin-top">
                <header class="w3-container bg-info text-white w3-center w3-padding-top">
                    <h3>{% trans "Personal Account" %}</h3>
                </header>
                <h3 class="w3-center w3-padding-top">{{ player.profile.private_account }} EMUs</h3>
            </div>
        </div>
    </div>

    {#    Need to add here the table with the results on the left and make it only available after the2 round#}

{% endblock %}

experiments/templates/experiments/index.html
{% extends "experiments/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "BEEL-Experiment" %}{% endblock %}

{% block headname %}{% trans "Brussels Experimental Economics Laboratory" %}{% endblock %}

{% block content %}
    <h1 class="w3-opacity w3-center">{% trans "Sign in to the experiment" %}</h1>
    <div class="w3-panel w3-white w3-card-2 w3-display-container w3-padding-16">
        <div class="w3-margin-top w3-large w3-center">
            {% if error_message %}<p class="w3-text-red"><strong>{{ error_message }}</strong></p>{% endif %}
            <form class="w3-border-0" id="login" action="{% url 'experiments:login' experiment_session.id %}"
                  method="post">
                {% csrf_token %}

                <input type="password" placeholder="{% trans "Enter Password" %}" name="password" required>
                <button type="submit" value="psw" class="btn btn-success">{% trans "Login" %}</button>
            </form>
            <label> {% trans "language" %}
                <select name="language" form="login">
                    <option value="en">English</option>
                    <option value="nl">Dutch</option>
                    <option value="fr">French</option>
                </select>
            </label>
        </div>
    </div>

{% endblock %}

experiments/templates/experiments/instructions.html
{% extends "experiments/base_no_footer.html" %}
{% load static %}
{% load i18n %}
{% load l10n %}

{% block title %}{% trans "BEEL-Instructions" %}{% endblock %}

{% block headname %}{% trans "Instructions" %}{% endblock %}

{% block content %}
    <div class="w3-panel w3-white w3-card-2 w3-display-container w3-padding-16">
        <div class="w3-light-grey w3-round-large w3-margin-bottom">
            <div class="w3-container w3-blue w3-round-large w3-center"
                 style="width:{{ fraction|unlocalize }}%">
                {{ instructions.number }}/{{ instructions.paginator.num_pages }}
            </div>
        </div>

        {% for instruction in instructions %}
            {{ instruction|safe }}<br/>
        {% endfor %}

        <div class="w3-bar w3-border w3-round">
            {% if instructions.has_previous %}
                <a href="?page={{ instructions.previous_page_number }}" class="w3-button" style="text-decoration: none">&#10094;
                    {% trans "Previous" %}</a>
            {% endif %}
            {% if instructions.has_next %}
                <a href="?page={{ instructions.next_page_number }}" class="w3-button w3-right"
                   style="text-decoration: none">{% trans "Next" %} &#10095;</a>
            {% else %}
                <a href="{% url 'experiments:test' player.session_id %}" class="w3-button w3-right w3-green"
                   style="text-decoration: none">{% trans "Next" %} &#10095;</a>
            {% endif %}
        </div>

    </div>

{% endblock %}

experiments/templates/experiments/wait.html
{% extends "experiments/base_game.html" %}
{% load static %}
{% load i18n %}


{% block title %}{% trans "Experiment | BEEL" %}{% endblock %}

{% block content %}

    <div class="w3-col w3-panel w3-white w3-card-2 w3-display-container w3-padding-16">
        <p>{% trans "Wait for the rest of the members of the group." %}</p>
    </div>

    <script>
        $(document).ready(function () {
            request();
        });
        function request() {
            console.log("create post is working!"); // sanity check
            $.ajax({
                url: "{% url 'experiments:sync' session_id %}", // the endpoint
                type: "POST", // http method
                data: {
                    session_id: {{session_id}},
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                }, // data sent with the post request

                // handle a successful response
                success: function (json) {
                    if (json['can_continue']) {
                        console.log("can_continue");
                        $(window).off("beforeunload");
                        $(location).attr('href', "{{ next }}")
                    }
                    console.log(json); // log the returned json to the console
                    console.log("success"); // another sanity check
                    setTimeout(request, 10000); // 10 seconds
                },

                // handle a non-successful response
                error: function (xhr, errmsg, err) {
                    console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                }
            });
        }


    </script>

{% endblock %}